name: flet_video
description: Flet Video control
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet-video/src/flutter/flet_video
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6

#  flet: ^0.70.0
  flet:
    git:
      path: packages/flet
      ref: v1
      url: https://github.com/flet-dev/flet.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0